(function(){
 const D=window.DiamondEnviosDomain,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dt=s=>s&&!isNaN(Date.parse(s))?new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Não registrado';
 const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 let filtros={},generation=0,rotaVista='',linkAberto='';
 async function render(){
  const host=document.getElementById('aba-corpo'),gen=++generation,route=location.hash||'#/admin/envios',param=D.readRoute(route);
  if(param.path!=='#/admin/envios')return;
  if(route!==rotaVista){rotaVista=route;filtros={q:param.q,fila:param.fila};}
  host.innerHTML='<p role="status">Consultando os links e as interações…</p>';
  let all;try{all=await STORE.listEnvios();}catch(e){if(gen===generation&&location.hash===route)host.innerHTML='<p role="alert">'+esc(e.message)+'</p><button id="env-retry">Tentar novamente</button>';host.querySelector('#env-retry')?.addEventListener('click',render);return;}
  if(gen!==generation||location.hash!==route)return;
  const select=(id,label,values)=>`<label>${label}<select id="env-${id}"><option value="">Todos</option>${[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option value="${esc(v)}" ${filtros[id]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
  host.innerHTML=`<section class="envios"><div class="env-heading"><div><h2>Propostas e acompanhamento</h2><p>Veja o que foi preparado e as interações registradas pelo cliente.</p></div><button class="btn-mini" id="env-refresh">↻ Atualizar</button></div>
   <div class="env-filters"><label class="env-search">Buscar<input id="env-q" placeholder="Cliente, unidade, número ou referência" value="${esc(filtros.q||'')}"></label><label>De<input type="date" id="env-de" value="${esc(filtros.de||'')}"></label><label>Até<input type="date" id="env-ate" value="${esc(filtros.ate||'')}"></label>${select('corretor','Corretor',all.map(e=>e.corretor))}${select('empresa','Empresa',all.map(e=>e.empresa))}${select('modalidade','Modalidade',all.map(e=>e.resumo?.modalidade||'Sem resumo'))}<button class="btn-mini" id="env-clear">Limpar filtros</button></div>
   <nav class="env-queues" aria-label="Filtrar interações">${[['','Todos'],['interesse','✓ Interesse'],['duvida','? Dúvidas'],['sem','Sem abertura registrada'],['conferir','⚠ Conferir dados'],['pendente','Retornos pendentes']].map(([k,l])=>`<button data-fila="${k}" aria-pressed="${(filtros.fila||'')===k}">${l}</button>`).join('')}</nav>
   <div id="env-totals" class="env-totals" role="status" aria-live="polite"></div><div id="env-results"></div>
   <p class="env-note">Link criado não confirma envio ou entrega no WhatsApp. Aberturas são acessos, não pessoas únicas. Uma leitura sem registro pode ocorrer. Os PDFs existentes permanecem como foram gerados.</p></section>`;
  function paint(){const items=D.filter(all,filtros);host.querySelector('#env-totals').innerHTML=`<span><b>${items.length}</b> de ${all.length} links</span><span><b>${items.reduce((s,e)=>s+(Number(e.views)||0),0)}</b> aberturas do link</span><span><b>${items.reduce((s,e)=>s+D.count(e,'abriu_pdf'),0)}</b> acessos ao PDF</span><span><b>${items.reduce((s,e)=>s+D.count(e,'interesse')+D.count(e,'duvida'),0)}</b> respostas</span>`;
   host.querySelectorAll('[data-fila]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.fila===(filtros.fila||''))));
   host.querySelector('#env-results').innerHTML=items.length?items.map(e=>{const a=D.activity(e),problems=D.issues(e,all);return `<article class="env-row" data-stage="${esc(e.acompanhamento?.etapa||'sem-etapa')}"><div><div class="env-ref">#${esc(String(e.numero||0).padStart(3,'0'))} · Ref. ${esc(e.id.slice(-8))}</div><h3>${esc(e.cliente||'Nome a conferir')}</h3><span>Unidade ${esc(e.unidade||'não informada')}</span><small>Link criado em ${dt(e.em)}</small></div><div><span class="env-label">Proposta</span><strong>${Number(e.valor)>0?money(e.valor):'Valor no PDF'}</strong><small>${esc(e.resumo?.modalidade||'Condições no PDF original')}</small>${e.resumo?.vaga?'<small>Vaga '+esc(e.resumo.vaga)+'</small>':''}</div><div><span class="env-label">Última interação</span><strong class="env-interaction env-interaction-${esc(a.tipo)}">${esc(D.labels[a.tipo]||a.tipo)}</strong><small>${dt(a.em)}</small>${problems.length?'<span class="env-alert">'+problems.length+' ponto(s) para conferir</span>':''}</div><div><span class="env-label">Responsável</span><strong>${esc(e.corretor||'Não informado')}</strong><small>${esc(e.empresa||'')}</small>${e.acompanhamento?'<small>'+esc(({pendente:'Retorno pendente',contato:'Em contato',concluido:'Concluído'})[e.acompanhamento.etapa]||'')+(e.acompanhamento.data?' · '+esc(e.acompanhamento.data.split('-').reverse().join('/')):'')+'</small>':''}<button class="btn-mini" data-detail="${esc(e.id)}">Ver acompanhamento</button></div></article>`;}).join(''):'<div class="vazio">Nenhum link corresponde aos filtros.</div>';
   host.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(all.find(e=>e.id===b.dataset.detail),all,b,paint));
  }
  for(const key of ['q','de','ate','corretor','empresa','modalidade'])host.querySelector('#env-'+key).addEventListener(key==='q'?'input':'change',e=>{filtros[key]=e.target.value;if(key==='q')atualizarQuery({q:filtros.q,dropEnvio:true});paint();});
  host.querySelectorAll('[data-fila]').forEach(b=>b.onclick=()=>{filtros.fila=b.dataset.fila;atualizarQuery({fila:filtros.fila,dropEnvio:true});paint();});
  host.querySelector('#env-clear').onclick=()=>{const explicitFila=D.readRoute(location.hash).filaExplicit;filtros=D.resetControls(host);if(!explicitFila)delete filtros.fila;atualizarQuery({fila:explicitFila?'':undefined,q:'',dropEnvio:true,explicitFila});paint();};host.querySelector('#env-refresh').onclick=render;paint();
  const deepRoute=location.hash||route;
  if(param.envio&&linkAberto!==deepRoute){const e=all.find(x=>x.id===param.envio);if(e){linkAberto=deepRoute;detail(e,all,null,paint);}}
 }
 function atualizarQuery({fila,q,dropEnvio=false,explicitFila=true}){const hash=D.writeRoute(location.hash||'#/admin/envios',{fila:explicitFila?fila:undefined,q,dropEnvio});history.replaceState(null,'',hash);rotaVista=hash;}
 function detail(e,all,opener,paint){
  const dlg=document.createElement('dialog');dlg.className='env-dialog';const url=window.P_URL+'/'+e.id,problems=D.issues(e,all),returnRoute=D.writeRoute(location.hash||'#/admin/envios',{dropEnvio:true});let original='';
  const events=[{tipo:'criacao',em:e.em},...(e.firstView?[{tipo:'abertura',em:e.firstView}]:[]),...(e.lastView&&e.lastView!==e.firstView?[{tipo:'abertura',em:e.lastView}]:[]),...(e.eventos||[])].sort((a,b)=>Date.parse(b.em)-Date.parse(a.em));
  dlg.innerHTML=`<div class="env-heading"><div><h2>${esc(e.cliente||'Nome a conferir')}</h2><p>Unidade ${esc(e.unidade)} · #${esc(e.numero)} · Ref. ${esc(e.id.slice(-8))}</p></div><button type="button" class="btn-mini" id="env-close" aria-label="Fechar acompanhamento">Fechar</button></div><div class="env-detail-body">
   <div class="env-actions"><a class="btn-mini" target="_blank" rel="noopener" href="${esc(url+'?preview=1')}">Prévia do cliente</a><a class="btn-mini" target="_blank" rel="noopener" href="${esc(url+'?pdf=1&preview=1')}">PDF original</a><button type="button" class="btn-mini" id="env-copy">Copiar mesmo link</button>${e.leadId&&e.vinculos?.cliente!==false?`<a class="btn-mini" href="#/cliente/${encodeURIComponent(e.leadId)}?voltar=${encodeURIComponent(returnRoute)}">Abrir cliente no CRM</a>`:''}${e.propostaId&&e.vinculos?.proposta!==false?`<a class="btn-mini" href="#/proposta/${encodeURIComponent(e.propostaId)}?voltar=${encodeURIComponent(returnRoute)}">Abrir cadastro da proposta</a>`:''}</div><p id="env-copy-status" role="status"></p>
   ${problems.length?'<aside class="env-problems"><b>Conferir os dados de origem</b><ul>'+problems.map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul><p>Nenhum nome ou vínculo foi alterado automaticamente.</p></aside>':''}
   <h3>Condições registradas neste link</h3>${e.resumo?`<p>${esc(e.resumo.modalidade)} · ${Number(e.valor)>0?money(e.valor):'Valor no PDF'}</p><dl class="env-terms">${(e.resumo.itens||[]).map(r=>'<div><dt>'+esc(r.rotulo)+'</dt><dd>'+esc(r.valor)+'</dd></div>').join('')}</dl><p>${esc(e.resumo.vaga?'Vaga '+e.resumo.vaga:'Vaga a escolher')} · Validade: ${esc(e.resumo.validade||'Consulte o PDF')}</p>`:'<p>Este link é anterior ao resumo de condições. Consulte o PDF original acima; as condições não serão recalculadas com valores de hoje.</p>'}
   <h3>Próximo passo</h3><form id="env-followup" class="env-followup"><label>Etapa<select name="etapa"><option value="pendente">Retorno pendente</option><option value="contato">Em contato</option><option value="concluido">Concluído</option></select></label><label>Retornar em<input type="date" name="data" value="${esc(e.acompanhamento?.data||'')}"></label><label class="env-followup-note">Observação interna<textarea name="nota" maxlength="2000" rows="3">${esc(e.acompanhamento?.nota||'')}</textarea></label><button class="btn-mini" type="submit">Salvar acompanhamento</button><p role="status" id="env-followup-status">${e.acompanhamento?'Última atualização: '+dt(e.acompanhamento.em):'Nenhum acompanhamento registrado.'}</p></form>
   <h3>Histórico de interações</h3><p>${Number(e.views)||0} abertura(s) do link. A lista inclui a primeira e a última abertura registradas, além dos acessos ao PDF e respostas.</p><ol class="env-timeline">${events.map(x=>'<li><b>'+esc(D.labels[x.tipo]||x.tipo)+'</b><time>'+dt(x.em)+'</time></li>').join('')}</ol></div>`;
  document.body.append(dlg);dlg.showModal();activeDialog=dlg;
  const f=dlg.querySelector('#env-followup');f.elements.etapa.value=e.acompanhamento?.etapa||'pendente';const formState=()=>JSON.stringify([...new FormData(f).entries()]);original=formState();dlg.dataset.savedForm=original;
  const isDirty=()=>formState()!==original;
  const closeIfSafe=()=>{if(isDirty()&&!confirm('Há alterações de acompanhamento não salvas. Fechar sem salvar?'))return false;dlg.close();return true;};
  dlg.querySelector('#env-close').onclick=closeIfSafe;
  dlg.addEventListener('cancel',ev=>{ev.preventDefault();closeIfSafe();});
  f.onsubmit=async ev=>{ev.preventDefault();const btn=f.querySelector('[type="submit"]'),status=dlg.querySelector('#env-followup-status');btn.disabled=true;status.setAttribute('role','status');status.textContent='Salvando…';try{const r=await STORE.api('anotarEnvio',{id:e.id,etapa:f.elements.etapa.value,data:f.elements.data.value,nota:f.elements.nota.value,comoCorretor:STORE.getUser()?.corretorAtivo?.nome||''});if(!r.ok)throw Error(r.erro||'Falha ao salvar.');e.acompanhamento=r.acompanhamento;status.textContent='Acompanhamento salvo.';original=formState();dlg.dataset.savedForm=original;paint();}catch(err){status.setAttribute('role','alert');status.textContent=err.message;}finally{btn.disabled=false;}};
  dlg.addEventListener('close',()=>{if(activeDialog===dlg)activeDialog=null;dlg.remove();const current=D.readRoute(location.hash);if(current.path==='#/admin/envios'&&current.envio===e.id){const listRoute=D.writeRoute(location.hash,{dropEnvio:true});history.replaceState(null,'',listRoute);rotaVista=listRoute;linkAberto='';}if(current.path==='#/admin/envios'){paint();document.querySelector('[data-detail="'+e.id+'"]')?.focus();}});
  dlg.querySelector('#env-copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);dlg.querySelector('#env-copy-status').textContent='Link copiado. O mesmo documento e histórico serão usados.';}catch{dlg.querySelector('#env-copy-status').textContent='Não foi possível copiar. Use a prévia para obter o link.';}};
 }
 let activeDialog=null;
 window.addEventListener('hashchange',ev=>{const dlg=activeDialog;if(!dlg)return;const f=dlg.querySelector('#env-followup'),changed=f&&JSON.stringify([...new FormData(f).entries()])!==dlg.dataset.savedForm,oldHash=new URL(ev.oldURL).hash||'#/admin/envios';if(changed&&!confirm('Há alterações de acompanhamento não salvas. Sair sem salvar?')){history.replaceState(null,'',oldHash);rotaVista=oldHash;return;}const oldRoute=D.readRoute(oldHash),nextRoute=D.readRoute(location.hash);if(oldRoute.envio&&nextRoute.envio!==oldRoute.envio)linkAberto='';dlg.close();});
 window.DiamondEnvios={render};
})();
