/* Reserva de apartamento: a confirmação é transacional no servidor. */
(()=>{
 const S=window.STORE,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=s=>s?new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Prazo não informado';
 let filtro='ativas',busca='',historico=[];
 const vencida=u=>u.reserva?.prazo&&Date.parse(u.reserva.prazo)<=Date.now();
 const api=b=>S.api('reservasPainel',b);
 const erro=(el,e)=>{el.textContent=e.message||'Não foi possível concluir.';el.setAttribute('role','alert');};
 async function render(){
  const root=document.querySelector('#aba-corpo');if(!root)return;
  root.innerHTML='<div class="rs-shell"><p role="status">Atualizando reservas…</p></div>';
  try{await S.pull();await S.pullReservas(true);if(S.status().estado==='erro')throw Error('Falha ao atualizar os dados. Tente novamente.');const r=await api({operacao:'listar'});historico=r.historico||[];if(!root.isConnected)return;pintar(root);}catch(e){if(!root.isConnected)return;root.innerHTML='<p class="rs-error" role="alert"></p><button id="rs-retry">Tentar novamente</button>';erro(root.querySelector('p'),e);root.querySelector('button').onclick=render;}
 }
 function pintar(root){
 const units=S.getUnidades(),pedidos=S.getReservas(),res=units.filter(u=>u.status==='Reservado');
 const totais={pedidos:pedidos.length,ativas:res.filter(u=>!vencida(u)).length,vencidas:res.filter(vencida).length,historico:historico.length};
 root.innerHTML=`<section class="rs-shell"><header class="rs-header"><div><h2>Reservas de apartamentos</h2><p>Cliente, responsável e prazo em um só lugar.</p></div><button class="btn" id="rs-new">+ Reservar apartamento</button></header><nav class="rs-tabs" aria-label="Situação das reservas">${Object.entries({pedidos:'Pedidos',ativas:'Ativas',vencidas:'Vencidas',historico:'Histórico'}).map(([k,v])=>`<button data-rs-filter="${k}" aria-pressed="${k===filtro}">${v} <b>${totais[k]}</b></button>`).join('')}</nav><div class="rs-tools"><input id="rs-search" aria-label="Buscar reservas" placeholder="Apartamento, cliente ou corretor" value="${esc(busca)}"><button id="rs-refresh">Atualizar</button></div><div id="rs-list"></div><p class="rs-note">Reservas vencidas continuam bloqueadas até você prorrogar ou cancelar. Escolher uma vaga é opcional.</p></section>`;
 root.querySelector('#rs-new').onclick=()=>abrir();root.querySelector('#rs-refresh').onclick=render;
 root.querySelectorAll('[data-rs-filter]').forEach(b=>b.onclick=()=>{filtro=b.dataset.rsFilter;pintar(root);});
 root.querySelector('#rs-search').oninput=e=>{busca=e.target.value;lista(root,units,pedidos,res);};lista(root,units,pedidos,res);
 }
 function lista(root,units,pedidos,res){
 const q=busca.toLocaleLowerCase('pt-BR'),box=root.querySelector('#rs-list');
 let rows=filtro==='pedidos'?pedidos.map(p=>({u:units.find(u=>u.id===p.unidadeId),p,r:p})):filtro==='historico'?historico.map(h=>({h,r:h.depois?.reserva||h.antes?.reserva||h.antes?.pedido||{},u:{unidade:h.unidade}})):res.filter(u=>filtro==='vencidas'?vencida(u):!vencida(u)).map(u=>({u,r:u.reserva||{cliente:u.compradorNome,corretor:u.vendedorNome}}));
 rows=rows.filter(x=>x.u&&[x.u.unidade,x.r.cliente,x.r.corretor,x.h?.motivo].join(' ').toLocaleLowerCase('pt-BR').includes(q));
 rows.sort((a,b)=>filtro==='historico'?b.h.em.localeCompare(a.h.em):filtro==='pedidos'?a.p.em.localeCompare(b.p.em):(a.r.prazo||'9999').localeCompare(b.r.prazo||'9999'));
 box.innerHTML=rows.length?rows.map((x,i)=>`<article class="rs-row"><div class="rs-unit">Apto <strong>${esc(x.u.unidade)}</strong>${x.r.vaga?`<small>${esc(x.r.vaga)}</small>`:''}</div><div class="rs-person"><strong>${esc(x.r.cliente||'Cliente não informado')}</strong><span>${esc(x.r.corretor||'Corretor não informado')}</span>${x.r.telefone?`<span>${esc(x.r.telefone)}</span>`:''}</div><div class="rs-deadline"><strong>${x.h?esc(({reservar:'Reserva confirmada',prorrogar:'Prazo prorrogado',cancelar:'Reserva cancelada',vender:'Convertida em venda',recusar:'Pedido recusado'})[x.h.acao]):x.p?'Aguardando aprovação':vencida(x.u)?'Prazo vencido':x.r.prazo?'Reservado':'Completar cadastro'}</strong><span>${esc(fmt(x.h?.em||x.p?.em||x.r.prazo))}</span>${x.h?`<small>${esc(x.h.por)} · ${esc(x.h.motivo)}</small>`:''}</div><div class="rs-actions">${x.h?'':(x.p?[['reservar','Aprovar'],['recusar','Recusar']]:[['prorrogar',x.r.prazo?'Prorrogar':'Completar'],['vender','Converter em venda'],['cancelar','Cancelar']]).map(([a,l])=>`<button data-rs-index="${i}" data-rs-action="${a}">${l}</button>`).join('')}</div></article>`).join(''):'<div class="rs-empty">Nenhuma reserva nesta seleção.</div>';
 box.querySelectorAll('[data-rs-index]').forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.rsIndex];abrir(x.u.id,b.dataset.rsAction,x.p);});
 }
 async function abrir(id,operacao='reservar',pedido){
 if(!S.podeVerPainel())return;
 document.querySelector('#rs-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='rs-dialog';dialog.className='rs-dialog';document.body.append(dialog);
 const opLabel={reservar:'Confirmar reserva',prorrogar:'Atualizar prazo',cancelar:'Cancelar reserva',vender:'Converter em venda',recusar:'Recusar pedido'};
 const units=S.getUnidades().filter(u=>id?u.id===id:u.status==='Disponível');
 if(!units.length){dialog.remove();return alert('Não há apartamentos disponíveis. Atualize o espelho.');}
 const edit=['reservar','prorrogar'].includes(operacao);
 dialog.innerHTML=`<form id="rs-form"><header><div><p class="rs-eyebrow">DIAMOND · RESERVAS</p><h2>${opLabel[operacao]}</h2></div><button type="button" id="rs-close" aria-label="Fechar">×</button></header><div class="rs-grid"><label>Apartamento<select name="unidadeId" ${id?'disabled':''}>${units.map(u=>`<option value="${esc(u.id)}">Apto ${esc(u.unidade)} · ${esc(u.status)}</option>`).join('')}</select></label>${edit?`<label>Usar cliente do CRM<select id="rs-crm"><option value="">Preencher manualmente</option>${S.getLeads().map((l,i)=>`<option value="${i}">${esc(l.cliente||'Sem nome')} · ${esc(l.clienteTel||l.unidade||'')}</option>`).join('')}</select></label>`:''}<label>Cliente<input name="cliente" maxlength="160" ${edit||operacao==='vender'?'required':''} ${edit||operacao==='vender'?'':'readonly'}></label><label>Telefone<input name="telefone" type="tel" maxlength="40" ${edit?'':'readonly'}></label><label>Corretor<input name="corretor" maxlength="160" ${edit?'required':'readonly'}></label><label>Imobiliária / empresa<input name="empresa" maxlength="160" ${edit?'':'readonly'}></label>${edit?'<label>Válida até<input name="prazo" type="datetime-local" required></label><label>Vaga de garagem<select name="vaga"><option value="">Escolher depois</option></select><small id="rs-vaga-info">Consultando disponibilidade…</small></label>':''}</div><label>Motivo / observações<textarea name="motivo" maxlength="300" rows="2" required></textarea></label><p id="rs-summary" class="rs-note"></p><p id="rs-error" role="status"></p><footer><button type="button" id="rs-back">Voltar</button><button class="btn" type="submit">${opLabel[operacao]}</button></footer></form>`;
 dialog.showModal();dialog.querySelector('#rs-close').onclick=()=>dialog.close();dialog.querySelector('#rs-back').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());
 const form=dialog.querySelector('form'),fields=form.elements;let u;
 function preencher(){u=units.find(x=>x.id===fields.unidadeId.value);if(operacao==='reservar')pedido=S.getReservas().find(p=>p.unidadeId===u.id);const r=u.reserva||{};fields.cliente.value=pedido?.cliente||r.cliente||u.compradorNome||'';fields.telefone.value=pedido?.telefone||r.telefone||'';fields.corretor.value=pedido?.corretor||r.corretor||u.vendedorNome||S.getUser()?.corretorAtivo?.nome||S.getUser()?.nome||'';fields.empresa.value=pedido?.empresa||r.empresa||u.vendedorEmpresa||'Domo';if(edit){fields.prazo.value=r.prazo?new Date(Date.parse(r.prazo)-new Date(r.prazo).getTimezoneOffset()*60000).toISOString().slice(0,16):'';}fields.motivo.value=operacao==='reservar'?'Reserva confirmada pela Domo':'';dialog.querySelector('#rs-summary').textContent=operacao==='cancelar'?'Ao confirmar, o apartamento e a vaga desta reserva serão liberados.':operacao==='vender'?'Confirme somente após conferir a venda. O comprador será registrado na unidade.':operacao==='recusar'?'O pedido será retirado da fila e a decisão ficará no histórico.':'A reserva será confirmada no sistema. Se escolher uma vaga, ela será reservada junto e enviada à planilha.';}
 preencher();fields.unidadeId.onchange=preencher;form.onsubmit=e=>e.preventDefault();form.querySelector('[type=submit]').disabled=true;
 if(edit){dialog.querySelector('#rs-crm').onchange=e=>{const l=S.getLeads()[+e.target.value];if(e.target.value===''||!l)return;fields.cliente.value=l.cliente||'';fields.telefone.value=l.clienteTel||'';fields.corretor.value=l.corretorNome||fields.corretor.value;fields.empresa.value=l.empresaNome||fields.empresa.value;};
 try{const data=await S.api('vagas',{operacao:'paraProposta'});if(!dialog.isConnected)return;fields.vaga.innerHTML='<option value="">Escolher depois</option>'+(data.vagas||[]).map(v=>`<option value="${esc(v.codigo)}">${esc(v.codigo)} · ${esc(v.pavimento)}</option>`).join('');if(u.reserva?.vaga){fields.vaga.add(new Option(u.reserva.vaga,u.reserva.vaga));fields.vaga.value=u.reserva.vaga;fields.vaga.disabled=true;}dialog.querySelector('#rs-vaga-info').textContent='Disponibilidade conferida novamente ao salvar.';}catch(e){dialog.querySelector('#rs-vaga-info').textContent='Não foi possível consultar vagas. Você pode reservar só o apartamento.';if(u.reserva?.vaga){fields.vaga.add(new Option(u.reserva.vaga,u.reserva.vaga));fields.vaga.value=u.reserva.vaga;fields.vaga.disabled=true;}}
 }
 form.querySelector('[type=submit]').disabled=false;
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;const body={operacao,unidadeId:u.id,revisao:u.atualizadoEm||'',pedidoEm:pedido?.em||null};for(const key of ['cliente','telefone','corretor','empresa','motivo','vaga'])body[key]=fields[key]?.value||'';if(edit)body.prazo=new Date(fields.prazo.value).toISOString();button.disabled=true;const msg=dialog.querySelector('#rs-error');msg.textContent='Confirmando…';try{await api(body);dialog.close();location.hash='#/admin/reservas';if(document.querySelector('#aba-corpo'))await render();}catch(e){erro(msg,e);button.disabled=false;}};
 }
 window.DiamondReservas={render,abrir};
})();
