/* Reserva de apartamento: a confirmação é transacional no servidor. */
(()=>{
 const S=window.STORE,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=s=>Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):s?'Prazo inválido':'Prazo não informado';
 let filtro='ativas',busca='',historico=[],unidadesPainel=null,pedidosPainel=null,consulta=0,rotaVista='',unidadeFiltro='';
 const filtrosValidos=new Set(['todas','pedidos','ativas','vencidas','incompletas','historico']);
 function lerRota(hash){const [path,query='']=String(hash||'#/admin/reservas').split('?'),params={};query.split('&').filter(Boolean).forEach(pair=>{const [k,v='']=pair.split('=');try{params[decodeURIComponent(k.replaceAll('+',' '))]=decodeURIComponent(v.replaceAll('+',' '));}catch{}});return{path,filtro:filtrosValidos.has(params.filtro)?params.filtro:'ativas',unidade:params.unidade||''};}
 function montarRota({filtro:status,unidade=''}={}){return '#/admin/reservas?filtro='+encodeURIComponent(status||'ativas')+(unidade?'&unidade='+encodeURIComponent(unidade):'');}
 const classeReserva=u=>{const t=u.reserva?.prazo?Date.parse(u.reserva.prazo):NaN;if(!Number.isFinite(t))return'incompletas';return t<=Date.now()?'vencidas':'ativas';};
 const vencida=u=>classeReserva(u)==='vencidas';
 const api=b=>S.api('reservasPainel',b);
 const erro=(el,e)=>{el.textContent=e.message||'Não foi possível concluir.';el.setAttribute('role','alert');};
 async function render(){
  const root=document.querySelector('#aba-corpo');if(!root)return;
  const rota=lerRota(location.hash);if(rota.path!=='#/admin/reservas')return;
  if(location.hash!==rotaVista){filtro=rota.filtro;unidadeFiltro=rota.unidade;rotaVista=location.hash;}
  root.innerHTML='<div class="rs-shell"><p role="status">Atualizando reservas…</p></div>';
  const atual=++consulta;
  try{const r=await api({operacao:'listar'});if(atual!==consulta||!root.isConnected||lerRota(location.hash).path!=='#/admin/reservas')return;historico=r.historico||[];unidadesPainel=r.unidades;pedidosPainel=r.pedidos;pintar(root);}catch(e){if(atual!==consulta||!root.isConnected||lerRota(location.hash).path!=='#/admin/reservas')return;root.innerHTML='<p class="rs-error" role="alert"></p><button id="rs-retry">Tentar novamente</button>';erro(root.querySelector('p'),e);root.querySelector('button').onclick=render;}

 }
 function pintar(root){
 const units=unidadesPainel||S.getUnidades(),pedidos=pedidosPainel||S.getReservas(),res=units.filter(u=>u.status==='Reservado');
 const totais={todas:res.length,pedidos:pedidos.length,ativas:res.filter(u=>classeReserva(u)==='ativas').length,vencidas:res.filter(u=>classeReserva(u)==='vencidas').length,incompletas:res.filter(u=>classeReserva(u)==='incompletas').length,historico:historico.length};
 const unidadeAlvo=unidadeFiltro?units.find(u=>u.id===unidadeFiltro):null;
 root.innerHTML=`<section class="rs-shell"><header class="rs-header"><div><h2>Reservas de apartamentos</h2><p>Cliente, responsável e prazo em um só lugar.</p></div><button class="btn" id="rs-new">+ Reservar apartamento</button></header><nav class="rs-tabs" aria-label="Situação das reservas">${Object.entries({todas:'Todas as reservas',pedidos:'Pedidos',ativas:'Ativas',vencidas:'Vencidas',incompletas:'Incompletas',historico:'Histórico'}).map(([k,v])=>`<button data-rs-filter="${k}" aria-pressed="${k===filtro}">${v} <b>${totais[k]}</b></button>`).join('')}</nav>${unidadeFiltro?`<p class="rs-route-note" role="status">${unidadeAlvo?`Filtro por apartamento ${esc(unidadeAlvo.unidade)} · `:'Apartamento não encontrado · '}<button type="button" id="rs-clear-unit">Remover filtro do apartamento</button></p>`:''}<div class="rs-tools"><input id="rs-search" aria-label="Buscar reservas" placeholder="Apartamento, cliente ou corretor" value="${esc(busca)}"><button id="rs-refresh">Atualizar</button></div><div id="rs-list"></div><p class="rs-note">Reservas vencidas continuam bloqueadas até você prorrogar ou cancelar. Escolher uma vaga é opcional.</p></section>`;
 root.querySelector('#rs-new').onclick=()=>abrir();root.querySelector('#rs-refresh').onclick=render;
 root.querySelectorAll('[data-rs-filter]').forEach(b=>b.onclick=()=>{filtro=b.dataset.rsFilter;location.hash=montarRota({filtro,unidade:unidadeFiltro});});
 const clearUnit=root.querySelector('#rs-clear-unit');if(clearUnit)clearUnit.onclick=()=>{unidadeFiltro='';location.hash=montarRota({filtro});};
 root.querySelector('#rs-search').oninput=e=>{busca=e.target.value;lista(root,units,pedidos,res);};lista(root,units,pedidos,res);
 }
 function lista(root,units,pedidos,res){
 const q=busca.toLocaleLowerCase('pt-BR'),box=root.querySelector('#rs-list'),unidadeAlvo=unidadeFiltro?units.find(u=>u.id===unidadeFiltro):null;
 let rows=filtro==='pedidos'?pedidos.map(p=>({u:units.find(u=>u.id===p.unidadeId),p,r:p})):filtro==='historico'?historico.map(h=>({h,r:h.depois?.reserva||h.antes?.reserva||h.antes?.pedido||{},u:{id:h.unidadeId,unidade:h.unidade}})):res.filter(u=>filtro==='todas'||filtro==='incompletas'&&classeReserva(u)==='incompletas'||filtro==='vencidas'&&classeReserva(u)==='vencidas'||filtro==='ativas'&&classeReserva(u)==='ativas').map(u=>({u,r:u.reserva||{cliente:u.compradorNome,corretor:u.vendedorNome}}));
 if(unidadeFiltro)rows=rows.filter(x=>(x.u?.id||x.p?.unidadeId||x.h?.unidadeId)===unidadeFiltro);
 rows=rows.filter(x=>x.u&&[x.u.unidade,x.r.cliente,x.r.corretor,x.h?.motivo].join(' ').toLocaleLowerCase('pt-BR').includes(q));
 rows.sort((a,b)=>filtro==='historico'?b.h.em.localeCompare(a.h.em):filtro==='pedidos'?a.p.em.localeCompare(b.p.em):(a.r.prazo||'9999').localeCompare(b.r.prazo||'9999'));
 box.innerHTML=rows.length?rows.map((x,i)=>`<article class="rs-row" data-state="${x.h?({reservar:'reservado',prorrogar:'reservado',cancelar:'cancelada',vender:'vendido',recusar:'recusado'})[x.h.acao]||'historico':x.p?'pedido':classeReserva(x.u)=='vencidas'?'vencida':classeReserva(x.u)=='incompletas'?'incompleta':'reservado'}"><div class="rs-unit">Apto <strong>${esc(x.u.unidade)}</strong>${x.r.vaga?`<small>${esc(x.r.vaga)}</small>`:''}</div><div class="rs-person"><strong>${esc(x.r.cliente||'Cliente não informado')}</strong><span>${esc(x.r.corretor||'Corretor não informado')}</span>${x.r.telefone?`<span>${esc(x.r.telefone)}</span>`:''}</div><div class="rs-deadline"><strong>${x.h?esc(({reservar:'Reserva confirmada',prorrogar:'Prazo prorrogado',cancelar:'Reserva cancelada',vender:'Convertida em venda',recusar:'Pedido recusado'})[x.h.acao]):x.p?'Aguardando aprovação':classeReserva(x.u)==='vencidas'?'Prazo vencido':classeReserva(x.u)==='incompletas'?'Prazo ausente ou inválido':'Reservado'}</strong><span>${esc(fmt(x.h?.em||x.p?.em||x.r.prazo))}</span>${x.h?`<small>${esc(x.h.por)} · ${esc(x.h.motivo)}</small>`:''}</div><div class="rs-actions">${x.h?'':(x.p?[['reservar','Aprovar'],['recusar','Recusar']]:[['prorrogar',classeReserva(x.u)==='incompletas'?'Completar':'Prorrogar'],['vender','Converter em venda'],['cancelar','Cancelar']]).map(([a,l])=>`<button class="${['cancelar','recusar'].includes(a)?'btn-danger':''}" data-rs-index="${i}" data-rs-action="${a}">${l}</button>`).join('')}</div></article>`).join(''):`<div class="rs-empty">${unidadeFiltro&&!unidadeAlvo?'Apartamento não encontrado.':unidadeAlvo?`Nenhum registro de ${esc(unidadeAlvo.unidade)} nesta seleção.`:'Nenhuma reserva nesta seleção.'}</div>`;
 box.querySelectorAll('[data-rs-index]').forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.rsIndex];abrir(x.u.id,b.dataset.rsAction,x.p);});
 }
 async function abrir(id,operacao='reservar',pedido){
 if(!S.podeVerPainel())return;
 document.querySelector('#rs-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='rs-dialog';dialog.className='rs-dialog';document.body.append(dialog);
 const opLabel={reservar:'Confirmar reserva',prorrogar:'Atualizar prazo',cancelar:'Cancelar reserva',vender:'Converter em venda',recusar:'Recusar pedido'};
 const units=(lerRota(location.hash).path==='#/admin/reservas'&&unidadesPainel?unidadesPainel:S.getUnidades()).filter(u=>id?u.id===id:u.status==='Disponível');
 if(!units.length){dialog.remove();return alert('Não há apartamentos disponíveis. Atualize o espelho.');}
 const edit=['reservar','prorrogar'].includes(operacao);
 dialog.innerHTML=`<form id="rs-form"><header><div><p class="rs-eyebrow">DIAMOND · RESERVAS</p><h2>${opLabel[operacao]}</h2></div><button type="button" id="rs-close" aria-label="Fechar">×</button></header><div class="rs-grid"><label>Apartamento<select name="unidadeId" ${id?'disabled':''}>${units.map(u=>`<option value="${esc(u.id)}">Apto ${esc(u.unidade)} · ${esc(u.status)}</option>`).join('')}</select></label>${edit?`<label>Usar cliente do CRM<select id="rs-crm"><option value="">Preencher manualmente</option>${S.getLeads().map((l,i)=>`<option value="${i}">${esc(l.cliente||'Sem nome')} · ${esc(l.clienteTel||l.unidade||'')}</option>`).join('')}</select></label>`:''}<label>Cliente<input name="cliente" maxlength="160" ${edit||operacao==='vender'?'required':''} ${edit||operacao==='vender'?'':'readonly'}></label><label>Telefone<input name="telefone" type="tel" maxlength="40" ${edit?'':'readonly'}></label><label>Corretor<input name="corretor" maxlength="160" ${edit?'required':'readonly'}></label><label>Imobiliária / empresa<input name="empresa" maxlength="160" ${edit?'':'readonly'}></label>${edit?'<label>Válida até<input name="prazo" type="datetime-local" required></label><label>Vaga de garagem<select name="vaga"><option value="">Escolher depois</option></select><small id="rs-vaga-info">Consultando disponibilidade…</small></label>':''}</div><label>Motivo / observações<textarea name="motivo" maxlength="300" rows="2" required></textarea></label><p id="rs-summary" class="rs-note"></p><p id="rs-error" role="status"></p><footer><button type="button" id="rs-back">Voltar</button><button class="btn ${['cancelar','recusar'].includes(operacao)?'btn-danger':''}" type="submit">${opLabel[operacao]}</button></footer></form>`;
 dialog.showModal();dialog.querySelector('#rs-close').onclick=()=>dialog.close();dialog.querySelector('#rs-back').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());
 const form=dialog.querySelector('form'),fields=form.elements;let u;
 function preencher(){u=units.find(x=>x.id===fields.unidadeId.value);if(operacao==='reservar')pedido=(lerRota(location.hash).path==='#/admin/reservas'&&pedidosPainel?pedidosPainel:S.getReservas()).find(p=>p.unidadeId===u.id);const r=u.reserva||{};fields.cliente.value=pedido?.cliente||r.cliente||u.compradorNome||'';fields.telefone.value=pedido?.telefone||r.telefone||'';fields.corretor.value=pedido?.corretor||r.corretor||u.vendedorNome||S.getUser()?.corretorAtivo?.nome||S.getUser()?.nome||'';fields.empresa.value=pedido?.empresa||r.empresa||u.vendedorEmpresa||'Domo';if(edit){const prazo=Date.parse(r.prazo);fields.prazo.value=Number.isFinite(prazo)?new Date(prazo-new Date(prazo).getTimezoneOffset()*60000).toISOString().slice(0,16):'';}fields.motivo.value=operacao==='reservar'?'Reserva confirmada pela Domo':'';dialog.querySelector('#rs-summary').textContent=operacao==='cancelar'?'Ao confirmar, o apartamento e a vaga desta reserva serão liberados.':operacao==='vender'?'Confirme somente após conferir a venda. O comprador será registrado na unidade.':operacao==='recusar'?'O pedido será retirado da fila e a decisão ficará no histórico.':'A reserva será confirmada no sistema. Se escolher uma vaga, ela será reservada junto e enviada à planilha.';}
 preencher();fields.unidadeId.onchange=preencher;form.onsubmit=e=>e.preventDefault();form.querySelector('[type=submit]').disabled=true;
 if(edit){dialog.querySelector('#rs-crm').onchange=e=>{const l=S.getLeads()[+e.target.value];if(e.target.value===''||!l)return;fields.cliente.value=l.cliente||'';fields.telefone.value=l.clienteTel||'';fields.corretor.value=l.corretorNome||fields.corretor.value;fields.empresa.value=l.empresaNome||fields.empresa.value;};
 try{const data=await S.api('vagas',{operacao:'paraProposta'});if(!dialog.isConnected)return;fields.vaga.innerHTML='<option value="">Escolher depois</option>'+(data.vagas||[]).map(v=>`<option value="${esc(v.codigo)}">${esc(v.codigo)} · ${esc(v.pavimento)}</option>`).join('');if(u.reserva?.vaga){fields.vaga.add(new Option(u.reserva.vaga,u.reserva.vaga));fields.vaga.value=u.reserva.vaga;fields.vaga.disabled=true;}dialog.querySelector('#rs-vaga-info').textContent='Disponibilidade conferida novamente ao salvar.';}catch(e){dialog.querySelector('#rs-vaga-info').textContent='Não foi possível consultar vagas. Você pode reservar só o apartamento.';if(u.reserva?.vaga){fields.vaga.add(new Option(u.reserva.vaga,u.reserva.vaga));fields.vaga.value=u.reserva.vaga;fields.vaga.disabled=true;}}
 }
 form.querySelector('[type=submit]').disabled=false;
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;const body={operacao,unidadeId:u.id,revisao:u.atualizadoEm||'',pedidoEm:pedido?.em||null};for(const key of ['cliente','telefone','corretor','empresa','motivo','vaga'])body[key]=fields[key]?.value||'';if(edit)body.prazo=new Date(fields.prazo.value).toISOString();button.disabled=true;const msg=dialog.querySelector('#rs-error');msg.textContent='Confirmando…';try{await api(body);dialog.close();location.hash='#/admin/reservas';if(document.querySelector('#aba-corpo'))await render();}catch(e){erro(msg,e);button.disabled=false;}};
 }
 window.DiamondReservas={render,abrir,lerRota,montarRota,classeReserva};
})();
