import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {backend,source,copy} from './helpers.mjs';
const ctx=vm.createContext({Date,Intl});vm.runInContext(source('envios-domain.js'),ctx);const D=ctx.DiamondEnviosDomain;
test('última interação considera resposta posterior ao link',()=>{const e={em:'2026-09-01',lastView:'2026-09-02',eventos:[{tipo:'abriu_pdf',em:'2026-09-03'},{tipo:'duvida',em:'2026-09-04'}]};assert.equal(D.activity(e).tipo,'duvida');});
test('filtra combinação de período, nome sem acento e corretor',()=>{const es=[{em:'2026-09-02T02:00:00Z',cliente:'João',corretor:'A'},{em:'2026-09-03T02:00:00Z',cliente:'João',corretor:'B'}];assert.equal(D.filter(es,{q:'joao',corretor:'A',ate:'2026-09-01'}).length,1);assert.equal(D.filter(es,{de:'2026-09-02',ate:'2026-09-01'}).length,0);});
test('sem abertura não inclui PDF aberto nem resposta',()=>{const es=[{em:'2026-09-01',views:0},{em:'2026-09-01',eventos:[{tipo:'abriu_pdf'}]},{em:'2026-09-01',eventos:[{tipo:'interesse'}]}];assert.equal(D.filter(es,{fila:'sem'}).length,1);});
test('qualidade usa evidência do servidor e distingue número antigo repetido',()=>{const e={cliente:'Cliente completo',leadId:'l',propostaId:'p',numero:7,vinculos:{cliente:true,proposta:true}};assert.equal(D.issues(e,[e]).length,0);assert.equal(D.issues(e,[e,{numero:7}]).length,1);});
const pdf=Buffer.from('%PDF-1.4\nfixture').toString('base64');
function fixture(){const b=backend();b.table('propostas').set('p-ok',{id:'p-ok',unidade:'1',cliente:'Cliente exemplo',neg:300000,corretorUsuario:'domo',corretor:'Teste',resumoEnvio:{modalidade:'Personalizado',validade:'2026-10-08',itens:[{rotulo:'Parcela final',valor:'R$ 150.000,00'}]}});return b;}
const body={base64:pdf,propostaId:'p-ok',unidade:'1',valor:300000,cliente:'Cliente exemplo',corretor:'Teste'};
test('upload sem proposta confirmada não cria PDF órfão',async()=>{const b=backend();assert.equal((await b.request('putPropostaPdf',body)).status,409);assert.equal(b.table('propostasPdf').size,0);});
test('upload não aceita outro apartamento, valor ou cliente',async()=>{for(const patch of [{unidade:'2'},{valor:42},{cliente:'Outro'}]){const b=fixture();assert.equal((await b.request('putPropostaPdf',{...body,...patch})).status,409);assert.equal(b.table('envios').size,0);}});
test('numeração simultânea e resumo imutável',async()=>{const b=fixture();const rs=await Promise.all(Array.from({length:15},()=>b.request('putPropostaPdf',body)));assert.equal(rs.filter(x=>x.ok).length,15);assert.equal(new Set(rs.map(x=>x.numero)).size,15);b.table('propostas').get('p-ok').resumoEnvio.itens[0].valor='Mudou';assert.equal([...b.table('envios').values()][0].resumo.itens[0].valor,'R$ 150.000,00');});
test('vínculo inexistente não gera link',async()=>{const b=fixture();assert.equal((await b.request('putPropostaPdf',{...body,leadId:'lead-ausente'})).status,409);});
test('PDFs não consomem limite de respostas e prévia não registra',async()=>{const b=backend();const id='pp-aaaaaaaaaaaaaaaa';b.table('envios').set(id,{nEv:90,views:0});b.table('propostasPdf').set(id,{base64:pdf});for(let i=0;i<60;i++)await b.publicGet({pdf:'1'});assert.equal((await b.pub({acao:'interesse'})).status,200);const count=b.table('enviosEv').size;await b.publicGet({pdf:'1',preview:'1'});assert.equal(b.table('enviosEv').size,count);for(let i=0;i<49;i++)assert.equal((await b.pub({acao:'duvida'})).status,200);assert.equal((await b.pub({acao:'interesse'})).status,429);});
test('landing expõe apenas resumo público, sem campos internos da proposta',async()=>{const b=backend();b.table('envios').set('pp-aaaaaaaaaaaaaaaa',{resumo:{modalidade:'SCP',itens:[]},telefone:'privado',propostaId:'p-ok',por:'interno'});const r=await b.publicGet({dados:'1'});const d=JSON.parse(r.body);assert.equal(d.resumo.modalidade,'SCP');assert.equal(d.telefone,undefined);assert.equal(d.por,undefined);});
test('acompanhamento preserva métricas e recusa acesso de cliente',async()=>{const b=backend(),id='pp-aaaaaaaaaaaaaaaa';b.table('envios').set(id,{por:'domo',views:12,numero:4});assert.equal((await b.request('anotarEnvio',{id,etapa:'contato',nota:'Ligar amanhã'})).ok,true);assert.equal(b.table('envios').get(id).views,12);assert.equal((await b.request('anotarEnvio',{id,etapa:'concluido'},'cliente')).status,403);assert.equal(b.table('envios').get(id).acompanhamento.etapa,'contato');});
test('confirma cliente e proposta antes do upload; conflito impede publicação',async()=>{const {store}=await import('./helpers.mjs');for(const fail of [false,true]){const calls=[];const{s,mem}=store(async(_,opts)=>{const body=JSON.parse(opts.body);calls.push(body.action);return{ok:true,json:async()=>fail&&body.action==='upsertProposta'?{conflito:true}:{ok:true,id:'pp-aaaaaaaaaaaaaaaa'}};});mem.set('dv_propostas',JSON.stringify([{id:'p-ok',corretorUsuario:'domo',corretor:'Teste'}]));mem.set('dv_leads',JSON.stringify([{id:'lead-ok',empresaUsuario:'domo',corretorNome:'Teste'}]));if(fail)await assert.rejects(s.enviarPropostaPdf(pdf,{propostaId:'p-ok',leadId:'lead-ok'}),/mudou/);else await s.enviarPropostaPdf(pdf,{propostaId:'p-ok',leadId:'lead-ok'});assert.deepEqual(calls,fail?['upsertLead','upsertProposta']:['upsertLead','upsertProposta','putPropostaPdf']);}});
