import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {backend,store,appTools,source} from './helpers.mjs';
// Returning full units without validating a session must fail this test.
test('unidades recusam consulta sem sessao',async()=>{const b=backend();assert.equal((await b.request('list',{},null)).status,403);});
test('sessao valida continua consultando as unidades',async()=>{const b=backend();const r=await b.request('list');assert.equal(r.status,200);assert.equal(r.unidades.length,2);});
test('cliente autorizado continua abrindo seu espelho',async()=>{const b=backend();assert.equal((await b.request('list',{},'cliente')).status,200);});
test('dois pedidos simultaneos preservam o primeiro e avisam o segundo',async()=>{const b=backend();const r=await Promise.all([b.request('pedirReserva',{unidadeId:'u-1',cliente:'A'}),b.request('pedirReserva',{unidadeId:'u-1',cliente:'B'})]);assert.equal(r.filter(x=>x.ok).length,1);assert.equal(r.filter(x=>x.jaPedida).length,1);assert.equal(b.table('reservas').get('u-1').cliente,'A');});
for(const id of ['u-inexistente','u-2'])test('nao cria pedido para '+id,async()=>{const b=backend();assert.ok((await b.request('pedirReserva',{unidadeId:id})).status>=400);assert.equal(b.table('reservas').size,0);});
test('falha de leitura da nuvem aparece no estado',async()=>{const{s}=store(async()=>{throw Error('offline')});await s.pull();assert.equal(s.status().estado,'erro');});
test('falha de CRM nao marca atualizacao completa como bem sucedida',async()=>{const{s,mem}=store(async(_,opts)=>{const a=JSON.parse(opts.body).action;if(a==='listLeads')throw Error('CRM indisponivel');return {ok:true,json:async()=>a==='list'?{unidades:[]}:a==='getCfg'?{cfg:{}}:a==='listPropostas'?{propostas:[]}:{reservas:[]}};});await s.pull();assert.equal(s.status().estado,'erro');assert.equal(mem.has('dv_lastsync'),false);});
test('leitura volta ao normal e registra a ultima atualizacao',async()=>{let fail=true;const{s,mem}=store(async(_,opts)=>{if(fail)throw Error('offline');const a=JSON.parse(opts.body).action;return {ok:true,json:async()=>a==='list'?{unidades:[]}:a==='getCfg'?{cfg:{}}:a==='listPropostas'?{propostas:[]}:a==='listLeads'?{leads:[]}:{reservas:[]}};});await s.pull();fail=false;await s.pull();assert.equal(s.status().estado,'ok');assert.ok(mem.get('dv_lastsync'));});
test('datas sem horario preservam o dia no Brasil',()=>{const a=appTools();assert.equal(a.fmtData('2026-08-07'),'07/08/2026');assert.equal(a.fmtData('2026-09-10T01:00:00Z'),'09/09/2026');});
test('SCP usa valor negociado e identidade unica para historico e envio',()=>{const a=appTools();assert.equal(typeof a.scpProposta,'function');const p=a.scpProposta({id:'u-1',unidade:'1',area:40},300000,{cliente:'Cliente Teste',tel:'',descPct:'10',corr:0,p12:true,nParc:'12'},{},{nome:'Teste',usuario:'domo'});assert.equal(p.neg,270000);assert.match(p.id,/^p-scp-1-/);assert.equal(p.inp.descPct,10);assert.equal(p.inp.nParc,12);});
test('SCP: desconto e quantidade de parcelas digitados valem na conta',()=>{const a=appTools();const s=a.scpCalcular(359196,{descPct:'7,5',p12:true,nParc:'18',p2412:true,nFix:'6',nCor:'30'},{correcaoMensal:0.005});assert.equal(Math.round(s.valor),332256);assert.equal(s.nParc,18);assert.equal(s.pParc.toFixed(2),'18458.68');assert.equal(s.nTot,36);assert.equal(s.pNom.toFixed(2),'9229.34');assert.equal(s.pCorN.toFixed(2),'10718.96');assert.equal(s.erro,'');});
test('SCP: quantidade invalida trava em vez de cair num 12 padrao',()=>{const a=appTools();for(const n of ['0','','2.5','241','abc']){const s=a.scpCalcular(300000,{p12:true,nParc:n},{});assert.equal(s.nParc,null,n);assert.ok(s.erro,n);}const d=a.scpCalcular(300000,{p2412:true,nFix:'12',nCor:'0'},{});assert.equal(d.nTot,0);assert.ok(d.erro);});
test('falha ao registrar interesse nao retorna sucesso',async()=>{const b=backend({failEvent:true});b.table('envios').set('pp-aaaaaaaaaaaaaaaa',{nEv:0});const r=await b.pub({acao:'interesse'});assert.ok(r.status>=500);assert.notEqual(r.ok,true);});
test('previa nao registra interesse mesmo se chamada diretamente',async()=>{const b=backend();b.table('envios').set('pp-aaaaaaaaaaaaaaaa',{nEv:0});await b.pub({acao:'interesse'},{preview:'1'});assert.equal(b.table('enviosEv').size,0);});
test('acao publica desconhecida e rejeitada',async()=>{const b=backend();b.table('envios').set('pp-aaaaaaaaaaaaaaaa',{nEv:0});assert.equal((await b.pub({acao:'inventada'})).status,400);});
test('envio de interesse confirmado fica registrado',async()=>{const b=backend();b.table('envios').set('pp-aaaaaaaaaaaaaaaa',{nEv:0});assert.equal((await b.pub({acao:'interesse'})).ok,true);assert.equal(b.table('enviosEv').size,1);});
// Use the actual storage adapter, replacing only its external database transport.
test('filtro de prefixo protege eventos de outros envios',async()=>{const rows=[{key:'pp-a-1'},{key:'pp-b-2'}];let q;const client={from:()=>{q={select:()=>q,eq:()=>q,order:()=>q,range:async()=>({data:rows,error:null})};return q;}};const ctx=vm.createContext({createClient:()=>client,Deno:{env:{get:()=>''}}});vm.runInContext(source('supabase/functions/_shared/blobs-shim.mjs').replace(/^import .+;\n/gm,'').replaceAll('export function','function').replaceAll('export const','const')+';globalThis.st=getStore;',ctx);const r=await ctx.st('enviosEv').list({prefix:'pp-a-'});assert.deepEqual(Array.from(r.blobs,x=>x.key),['pp-a-1']);});
test('cliente so leitura nao consulta CRM durante atualizacao',async()=>{const called=[];const{s,mem}=store(async(_,opts)=>{const a=JSON.parse(opts.body).action;called.push(a);return{ok:true,json:async()=>a==='list'?{unidades:[]}:{cfg:{}}};});s.setUser({usuario:'cliente',senhaHash:'fake',papel:'cliente'},true);await s.pull();assert.deepEqual(called,['list','getCfg']);assert.equal(s.status().estado,'ok');assert.ok(mem.get('dv_lastsync'));});
test('API abandona requisicao travada e permite tentar novamente',async()=>{let attempt=0;const{s,ctx}=store(async(_,opts)=>{attempt++;if(attempt===1)return new Promise((_,reject)=>opts.signal.addEventListener('abort',()=>reject(Error('abort'))));return{ok:true,json:async()=>({ok:true})};});ctx.setTimeout=(fn)=>setTimeout(fn,5);await assert.rejects(s.api('ping'),e=>e.status===408);assert.equal((await s.api('ping')).ok,true);});
test('adaptador usa INSERT e preserva a reserva existente',async()=>{const rows=new Map();let q;const client={from:()=>({insert:async r=>{if(rows.has(r.store+'/'+r.key))return{error:{code:'23505'}};rows.set(r.store+'/'+r.key,r);return{error:null};}})};const ctx=vm.createContext({createClient:()=>client,Deno:{env:{get:()=>''}}});vm.runInContext(source('supabase/functions/_shared/blobs-shim.mjs').replace(/^import .+;\n/gm,'').replaceAll('export function','function').replaceAll('export const','const')+';globalThis.st=getStore;',ctx);const s=ctx.st('reservas');assert.equal(await s.insertJSON('u-1',{cliente:'A'}),true);assert.equal(await s.insertJSON('u-1',{cliente:'B'}),false);assert.equal(rows.get('reservas/u-1').valor.cliente,'A');});
test('proposta emitida a noite usa a data local ao reabrir',()=>{const app=source('app.js');const body=app.slice(app.indexOf('    const montaP ='),app.indexOf('    const saud ='));const{s}=store(async()=>({ok:true,json:async()=>({})}));const c=vm.createContext({Date,STORE:s,d:{criadoEm:'2026-09-10T02:30:00.000Z',cliente:'Teste',clienteTel:'',propostaId:'p-teste',entradaPct:20,finalPct:30,parcelas:24},u:{id:'u-1',unidade:'1',area:40},user:{nome:'Teste'},cfg:{},vt:300000,balQtdeEfetiva:()=>0});vm.runInContext(body+';globalThis.proposta=montaP(true);',c);assert.equal(c.proposta.inp.dataProposta,'2026-09-09');});
