// Preview local com registros fictícios e transporte restrito ao próprio servidor.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {backend,source} from './helpers.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));const b=backend();
b.table('unidades').set('u-1',{id:'u-1',unidade:'1',status:'Disponível',precoBase:300000,area:40,andar:4,desconto:0,atualizadoEm:'2026-09-09T20:00:00Z'});
b.table('unidades').set('u-2',{id:'u-2',unidade:'2',status:'Vendido',precoBase:350000,area:45,andar:4,desconto:0,atualizadoEm:'2026-09-09T20:00:00Z'});
const cfg={dataTabela:'09/09/2026',versao:'Prévia local',atualizadoEm:'2026-09-09T20:00:00Z',correcaoMensal:.006,correcaoDesde:13,balQtde:0,balValor:10000,balPrimeiro:6,balIntervalo:6,chavesMes:36,diaVenc:10};b.table('cfg').set('cfg',cfg);
b.table('leads').set('lead-teste',{id:'lead-teste',cliente:'Cliente de teste',clienteTel:'',unidade:'1',primeiroContato:'2026-08-07',proximoContato:'2026-09-11',empresaUsuario:'domo',empresaNome:'Domo',corretorNome:'Teste',estagio:'proposta',temp:'morno',criadoEm:'2026-08-07T15:00:00Z',atualizadoEm:'2026-09-09T20:00:00Z'});
const session={usuario:'domo',senhaHash:'fake',nome:'Domo',papel:'corretor',ehMaster:true,temSenhaEquipe:true,corretores:[{nome:'Teste'}],corretorAtivo:{nome:'Teste'},empresa:'Domo'};
const port=8767;const base='http://127.0.0.1:'+port;const events=[];
http.createServer(async(req,res)=>{try{const u=new URL(req.url,base);let text='',type='application/json';
 if(u.pathname==='/api/dmd-api'){let body='';for await(const chunk of req)body+=chunk;const data=JSON.parse(body||'{}');if(!['list','getCfg','listLeads','listReservas','listPropostas','listEnvios','getFoto'].includes(data.action))events.push({action:data.action,body:data});const r=await b.request(data.action,data,data.auth?.usuario||null);res.statusCode=r.status;text=JSON.stringify(r);}
 else if(u.pathname.startsWith('/api/dmd-p/')){text=JSON.stringify({cliente:'Cliente de teste',corretor:'Corretor de teste',valor:270000,unidade:'1',area:40,andar:4,em:'2026-09-09T20:00:00Z',whats:'5511999999999',ok:true});}
 else if(u.pathname==='/audit-state'){text=JSON.stringify({events,propostas:[...b.table('propostas').values()],reservas:[...b.table('reservas').values()]});}
 else if(u.pathname==='/fixture.js'){type='application/javascript';text=`localStorage.setItem('dv_user',${JSON.stringify(JSON.stringify(session))});localStorage.setItem('dv_owner','domo');localStorage.setItem('dv_fila','[]');`;}
 else if(u.pathname==='/config.js'){type='application/javascript';text=`window.API_BASE=${JSON.stringify(base+'/api')};window.APP_TOKEN='fake';window.P_URL=${JSON.stringify(base+'/api/dmd-p')};`;}
 else{const name=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname).slice(1);const filename=path.resolve(root,name);if(!filename.startsWith(root)||!fs.existsSync(filename)||!fs.statSync(filename).isFile()){res.statusCode=404;text='Not found';}else{const ext=path.extname(filename);type={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webmanifest':'application/manifest+json'}[ext]||'application/octet-stream';let data=fs.readFileSync(filename);if(name==='index.html')data=Buffer.from(data.toString().replace('<script src="config.js">','<script src="fixture.js"></script><script src="config.js">'));if(name==='p.html')data=Buffer.from(data.toString().replace('https://reoghclxripktzpdwhiy.supabase.co/functions/v1/dmd-p/',base+'/api/dmd-p/'));text=data;}}
 res.setHeader('Content-Type',type);res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"connect-src 'self' data:; object-src 'none'");res.end(text);
 }catch(e){res.statusCode=500;res.end(JSON.stringify({erro:e.message}));}}).listen(port,'127.0.0.1',()=>console.log('Prévia isolada em '+base));
