import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {reconcile as rec,confirm as conf} from '../supabase/functions/dmd-sheets/sync.mjs';
const SHEET='planilha-de-teste';
const reconcile=(...a)=>rec(...a,SHEET),confirm=(...a)=>conf(...a,SHEET);
const V=createRequire(import.meta.url)('../vagas-domain.js');
function source(){const f={spreadsheetId:SHEET,vinculos:[['Apartamento','Tipologia / Área','Cliente / Proprietário','Vaga Vinculada','Confirmação (V/R)','Pavimento da Vaga','Status','Contratos','Início','Término','Contador de Dias','']],gestao:[['Vaga','Pavimento','Apartamento','Cliente / Proprietário','Status','Data da Reserva','Prazo de Expiração','Observações']]};for(let i=1;i<=82;i++){f.vinculos.push(['Apto '+(400+i),'40 m²','','','','','Disponível','','','','formula','']);f.gestao.push([V.codigo(i),V.PISOS[V.piso(i)].nome,'','','Disponível','','','']);}return f;}
function local(f){const s=V.importar(f);s.ajustes={V01:V.validarAjuste('V01',{situacao:'vendida',cliente:'Teste',apartamento:'Apto 401',contrato:'Finalizado',motivo:'conferido'},s)};return s;}
function apply(f,p){for(const x of p.patches){const m=x.celula.match(/([A-Z])(\d+)/);const rows=x.aba==='Gestão de Vagas'?f.gestao:f.vinculos;rows[+m[2]-8][m[1].charCodeAt(0)-66]=x.depois;}return f;}
test('Diamond -> ambas as abas, confirmação, idempotência e fórmulas intactas',()=>{const f=source(),s=local(f),p=reconcile(V,s,f,'agora','x');assert.ok(p.sync.pendente);assert.ok(p.sync.pendente.patches.every(x=>!/^L|^M/.test(x.celula)));apply(f,p.sync.pendente);const done=confirm(V,p,f,'x','depois');assert.equal(done.sync.pendente,null);assert.equal(V.efetivas(done)[0].situacao,'vendida');assert.equal(reconcile(V,done,f,'depois','y').sync.pendente,null);assert.equal(f.vinculos[1][10],'formula');});
test('planilha -> Diamond após confirmação anterior',()=>{const f=source(),p=reconcile(V,local(f),f,'a','x');apply(f,p.sync.pendente);const done=confirm(V,p,f,'x','b');f.gestao[1][3]='Novo';f.vinculos[1][2]='Novo';const next=reconcile(V,done,f,'c','y');assert.equal(next.ajustes.V01,undefined);assert.equal(V.efetivas(next)[0].cliente,'Novo');});
test('edições simultâneas não sobrescrevem nenhuma ponta',()=>{const f=source(),s=local(f);f.gestao[1][7]='Alterado na planilha';const p=reconcile(V,s,f,'a','x');assert.equal(p.sync.pendente,null);assert.deepEqual(p.sync.conflitos,['V01']);assert.equal(V.efetivas(p)[0].situacao,'conferir');});
test('não confirma escrita parcial nem aceita outra planilha',()=>{const f=source(),p=reconcile(V,local(f),f,'a','x');assert.throws(()=>confirm(V,p,f,'x','b'),/confirmou/);assert.throws(()=>reconcile(V,p,{...f,spreadsheetId:'outra'},'a','x'),/autorizada/);});
test('não transfere vaga que já está vinculada na planilha',()=>{const f=source(),s=local(f);f.vinculos[1][3]='V02';const raw=V.importar(f);s.vagas=raw.vagas;s.ajustes.V01.assinatura=raw.vagas[0].assinatura;const p=reconcile(V,s,f,'a','x');assert.deepEqual(p.sync.conflitos,['V01']);assert.equal(p.sync.pendente,null);});

test('coluna vazia do CSV não gera falso conflito',()=>{const f=source(),s=local(f);const old=JSON.parse(s.ajustes.V01.assinatura);old.gestao['']='';s.ajustes.V01.assinatura=JSON.stringify(old);const p=reconcile(V,s,f,'a','x');assert.deepEqual(p.sync.conflitos,[]);assert.ok(p.sync.pendente);});

test('aba única define situação e vincula apartamento sem depender da aba removida',()=>{const f=source();delete f.gestao;f.vinculos[1][2]='Cliente';f.vinculos[1][3]='V19';f.vinculos[1][4]='V';f.vinculos[1][6]='Vinculada / Vendida';const s=V.importar(f);assert.equal(s.fonte.abaUnica,true);assert.equal(s.vagas[18].situacao,'vendida');assert.equal(s.vagas[18].apartamento,'Apto 401');assert.equal(s.vagas[56].situacao,'disponivel');assert.equal(s.vagas.filter(v=>v.alertas.length).length,0);});
test('salvar no Diamond atualiza somente a aba única e confirma retorno',()=>{const f=source();delete f.gestao;const s=local(f),p=reconcile(V,s,f,'a','x');assert.ok(p.sync.pendente.patches.every(x=>x.aba==='Vagas de Garagem'));apply(f,p.sync.pendente);const done=confirm(V,p,f,'x','b');assert.equal(done.sync.pendente,null);assert.equal(V.efetivas(done)[0].cliente,'Teste');});
